package com.communityhelp.app.common.exceptions;

public enum ErrorCode {

    VALIDATION_ERROR,
    INVALID_REQUEST,
    TYPE_MISMATCH,
    MALFORMED_JSON,

    INVALID_CREDENTIALS,
    AUTHENTICATION_REQUIRED,
    ACCESS_DENIED,
    INVALID_TOKEN,
    JWT_EXPIRED,
    EMAIL_NOT_VERIFIED,

    RESOURCE_NOT_FOUND,
    CONFLICT,
    DATABASE_CONSTRAINT,

    INTERNAL_ERROR,

    RATE_LIMIT_EXCEEDED,

    DONATION_DUPLICATE_TITLE,
    HELP_REQUEST_DUPLICATE_TITLE,
    EMAIL_ALREADY_EXISTS
}
