services:
  # PostgreSQL + PostGIS
  db:
    image: postgis/postgis:18-3.6
    container_name: postgres-db-community-help
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-config/postgres-init.sql:/docker-entrypoint-initdb.d/init-postgis.sql

  # Adminer
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
    depends_on:
      - db

  # TODO zookeper
  # TODO kafka
#  app:
#    build: .
#    container_name: community-help-api
#    restart: always
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE: prod
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#      JWT_SECRET: ${JWT_SECRET}
#      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
#      JWT_EXPIRED_IN: ${JWT_EXPIRED_IN}
#      ADMIN_EMAIL: ${ADMIN_EMAIL}
#      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
#      OPENROUTE_API_KEY: ${OPENROUTE_API_KEY}

volumes:
  postgres_data: