# ================================
# DESARROLLO
# ================================
FROM maven:3.9.9-eclipse-temurin-21
WORKDIR /app

# Copia solo el pom.xml primero para cachear dependencias
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copia el resto del código
COPY src ./src

# Arranca con spring-boot:run para hot-reload
CMD ["mvn", "spring-boot:run"]