# base, común a dev y prod
services:
  api:
    container_name: community-help-api
    ports:
      - "${API_PORT:-8080}:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgis/postgis:18-3.6
    container_name: community-help-db
    ports:
      - "5432:5432"